[package]
name = "takon"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
  "examples/*"
]

[dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
winit = "0.30.5"
